# Generated by Django 2.1 on 2019-06-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Полное имя автора')),
                ('date_born', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('date_die', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
                ('biography', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Биография')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='upload/author_photo/', verbose_name='Фотография')),
            ],
        ),
    ]
