# Generated by Django 2.1 on 2019-06-29 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_author_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название книги')),
                ('publication', models.TextField(max_length=10, verbose_name='Год издания')),
                ('file', models.FileField(blank=True, null=True, upload_to='book_file', verbose_name='Файл с текстом')),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_photo', verbose_name='Обложка')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Author', verbose_name='Автор')),
            ],
        ),
    ]
